FROM python:3.10.6

WORKDIR /application

RUN apt-get update &&\
    apt-get install -y golang-go git make libffi-dev gcc &&\
    git clone https://github.com/go-enry/go-enry

SHELL ["/bin/bash", "-c"]

RUN cd go-enry/python &&\
    pushd .. && make static && popd &&\
    pip install -r requirements.txt &&\
    python build_enry.py &&\
    python setup.py bdist_wheel &&\
    pip install ./dist/*.whl

COPY  requirements.txt /application/requirements.txt

RUN pip install -r /application/requirements.txt

COPY . .